name: shokher_bari
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  fluttertoast: ^8.0.8
  uuid: ^3.0.5
  carousel_pro_nullsafety: ^1.0.2
  provider: ^6.0.2
  im_stepper: ^0.1.3
  image_picker: ^0.8.4+8

  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.7
  firebase_storage: ^10.2.7
  flutterfire_ui: ^0.3.4
  firebase_auth: ^3.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins_Extra_Light.ttf
        - asset: assets/fonts/Poppins_Medium.ttf
        - asset: assets/fonts/Poppins_Regular.ttf
          style: normal


