// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxKhAJIGIRYGDNUookwxLnwWYit64zR4k',
    appId: '1:658701742286:web:395bb1099bd10146b5209f',
    messagingSenderId: '658701742286',
    projectId: 'shokher-bari-cbb52',
    authDomain: 'shokher-bari-cbb52.firebaseapp.com',
    storageBucket: 'shokher-bari-cbb52.appspot.com',
    measurementId: 'G-8WYWCEN58Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM7W4U4Yt4PmoXCuymYz4ptDZZO4K7qtA',
    appId: '1:658701742286:android:f5b090b3cdeaa175b5209f',
    messagingSenderId: '658701742286',
    projectId: 'shokher-bari-cbb52',
    storageBucket: 'shokher-bari-cbb52.appspot.com',
  );
}
